[build]
target = ["x86_64-pc-windows-msvc", "i686-pc-windows-msvc"]

[target.x86_64-pc-windows-msvc]
# No specific settings needed for 64-bit

[target.i686-pc-windows-msvc]
# 32-bit executable will be statically link
rustflags = ["-C", "target-feature=+crt-static"]